name: Kernel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        run: |
          curl -LO https://github.com/torvalds/linux/archive/refs/heads/master.zip
          unzip master.zip
          mv linux-master/* .
      - name: Build kernel
        run: |
          sudo apt update
          sudo apt install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils -y
          make defconfig
          make -j$(nproc)
      - name: Zip up
        run: |
          cd arch/x86 
          tar czvf ../../x86.tar.gz .
          cd ../..
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vmlinux
            x86.tar.gz
            
