name: Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VERSION: 6.15

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        run: |
          set -x
          curl -Lso linux.tar.gz https://github.com/torvalds/linux/archive/refs/tags/v${VERSION}.tar.gz
          tar xf linux.tar.gz
          rm linux.tar.gz
          mv linux-${VERSION}/* .
          mv linux-${VERSION}/.* .
          rmdir linux-${VERSION}
      - name: Build kernel
        run: |
          set -x
          make defconfig
          make -j$(nproc)
      - name: Zip up modules
        run: find . -name '*.ko' | cpio -H newc -o | gzip > modules.cpio.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          tag_name: v${{env.VERSION}}
          name: Linux kernel ${{env.VERSION}}
          files: |
            arch/x86/boot/bzImage
            modules.cpio.gz
            
