name: Kernel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *'
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Clone
        run: |
          git clone --depth=1 --single-branch --branch=master https://github.com/torvalds/linux.git
          mv linux/* .
          mv linux/.* .
          rmdir linux
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils -y
      - name: Build kernel
        run: |
          make defconfig
          make -j$(nproc)
      - name: Zip up modules
        run: |
          find . -name '*.ko' | cpio -H newc -o | gzip > modules.cpio.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: Build on ${{ steps.date.outputs.date }}
          files: |
            arch/x86/boot/bzImage
            modules.cpio.gz
            
